package check

import (
	"context"
	"go/ast"
	"os"
	"path/filepath"
	"strings"

	"github.com/gohaisee/refgrade/internal/astutil"
)

const gqlResolverMaxLines = 500

var (
	gqlGates = []string{"gqlgen", "graphql-go", "graphql"}

	gqlgenGeneratedMarker = "Code generated by github.com/99designs/gqlgen"

	complexityLimitHints = []string{
		"FixedComplexityLimit", "ComplexityLimit", "MaxDepth",
		"depth.Limit", "graphql.MaxDepth", "SetComplexityLimit",
	}

	introspectionHints = []string{
		"extension.Introspection", "Introspection{}", "EnableIntrospection", "IntrospectionEnabled",
	}

	playgroundHints = []string{
		"playground.Handler", "graphiql.Handler", "graphql-playground", "/playground", "PlaygroundHandler",
	}

	recoverHints = []string{
		"defer recover", "recover()", "Recovery(", "Recoverer(", "PanicHandler", "OnPanic",
	}

	authHints = []string{
		"Auth", "Authorize", "GetUser", "CurrentUser", "Actor", "Owner", "Permission", "CanAccess",
	}

	querySizeLimitHints = []string{
		"MaxBytesReader", "LimitReader", "maxQuerySize", "MaxQueryLength", "querySizeLimit",
	}

	dbQueryMethods = map[string]struct{}{
		"Query": {}, "QueryRow": {}, "QueryContext": {}, "QueryRowContext": {},
		"Exec": {}, "ExecContext": {},
		"Get": {}, "Select": {}, "Find": {}, "First": {}, "Take": {},
		"Scan": {}, "Raw": {}, "Where": {},
	}

	batchHints = []string{"dataloader", "DataLoader", "LoadAll", "LoadMany", "batch", "Batch"}
)

// db driver import in resolver package
type Gql01 struct{ Base }

func NewGql01() *Gql01 {
	return &Gql01{Base: Base{meta: Meta{ID: "gql-01", Gates: gqlGates, Domain: "graphql", DefaultSeverity: SeverityFail}}}
}

func (c *Gql01) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := poolFor(mod, astutil.DefaultFilter())
	if err != nil {
		return nil, err
	}
	var findings []Finding
	for _, f := range pool.Files {
		if !isResolverFilePath(f.RelPath) || astutil.IsTestFile(f.RelPath) || isGqlGeneratedFile(f.RelPath) {
			continue
		}
		for _, imp := range f.Imports {
			if _, ok := dbDriverImports[imp]; ok {
				findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityFail), f.RelPath, 1))
				break
			}
		}
	}
	return findings, nil
}

// db call inside loop in resolver
type Gql02 struct{ Base }

func NewGql02() *Gql02 {
	return &Gql02{Base: Base{meta: Meta{ID: "gql-02", Gates: gqlGates, Domain: "graphql", DefaultSeverity: SeverityWarn}}}
}

func (c *Gql02) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := poolFor(mod, astutil.Filter{SkipTestFiles: true})
	if err != nil {
		return nil, err
	}
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !isHandWrittenResolverFile(f) {
			return true
		}
		body := loopBody(n)
		if body == nil {
			return true
		}
		ast.Inspect(body, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok || !isDbQueryCall(f, call) || fileHasBatchHint(f) {
				return true
			}
			findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityWarn), f.RelPath, pool.Line(call)))
			return true
		})
		return true
	})
	return findings, nil
}

// hand-edited gqlgen output files
type Gql03 struct{ Base }

func NewGql03() *Gql03 {
	return &Gql03{Base: Base{meta: Meta{ID: "gql-03", Gates: []string{"gqlgen"}, Domain: "graphql", DefaultSeverity: SeverityFail}}}
}

func (c *Gql03) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	var findings []Finding
	for _, gf := range mod.GoSourceFiles() {
		if !isGqlGeneratedFile(gf.RelPath) {
			continue
		}
		data, err := os.ReadFile(gf.Path)
		if err != nil {
			continue
		}
		if strings.Contains(string(data), gqlgenGeneratedMarker) {
			continue
		}
		findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityFail), gf.RelPath, 1))
	}
	return findings, nil
}

// no complexity or depth limit in server setup
type Gql04 struct{ Base }

func NewGql04() *Gql04 {
	return &Gql04{Base: Base{meta: Meta{ID: "gql-04", Gates: gqlGates, Domain: "graphql", DefaultSeverity: SeverityWarn}}}
}

func (c *Gql04) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	if !moduleHasGraphQLServer(mod) {
		return nil, nil
	}
	pool, err := poolFor(mod, astutil.Filter{SkipTestFiles: true})
	if err != nil {
		return nil, err
	}
	if moduleHasHint(pool, complexityLimitHints) {
		return nil, nil
	}
	file, line, ok := firstGraphQLServerSetup(pool)
	if !ok {
		return []Finding{finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityWarn), "go.mod", 1)}, nil
	}
	return []Finding{finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityWarn), file, line)}, nil
}

// introspection without env or dev gate
type Gql05 struct{ Base }

func NewGql05() *Gql05 {
	return &Gql05{Base: Base{meta: Meta{ID: "gql-05", Gates: gqlGates, Domain: "graphql", DefaultSeverity: SeverityWarn}}}
}

func (c *Gql05) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := poolFor(mod, astutil.Filter{SkipTestFiles: true})
	if err != nil {
		return nil, err
	}
	var findings []Finding
	for _, f := range pool.Files {
		if !fileHasIntrospection(f) || hasDevOrEnvGuard(string(f.Src)) {
			continue
		}
		findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityWarn), f.RelPath, introspectionLine(f)))
	}
	return findings, nil
}

// playground route without dev gate
type Gql06 struct{ Base }

func NewGql06() *Gql06 {
	return &Gql06{Base: Base{meta: Meta{ID: "gql-06", Gates: gqlGates, Domain: "graphql", DefaultSeverity: SeverityFail}}}
}

func (c *Gql06) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := poolFor(mod, astutil.Filter{SkipTestFiles: true})
	if err != nil {
		return nil, err
	}
	var findings []Finding
	for _, f := range pool.Files {
		if !fileHasPlayground(f) || hasDevOrEnvGuard(string(f.Src)) {
			continue
		}
		findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityFail), f.RelPath, playgroundLine(f)))
	}
	return findings, nil
}

// map[string]interface{} in hand-written resolvers
type Gql07 struct{ Base }

func NewGql07() *Gql07 {
	return &Gql07{Base: Base{meta: Meta{ID: "gql-07", Gates: []string{"gqlgen"}, Domain: "graphql", DefaultSeverity: SeverityWarn}}}
}

func (c *Gql07) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := poolFor(mod, astutil.Filter{SkipTestFiles: true})
	if err != nil {
		return nil, err
	}
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !isHandWrittenResolverFile(f) || !isMapStringInterface(n) {
			return true
		}
		findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityWarn), f.RelPath, pool.Line(n)))
		return true
	})
	return findings, nil
}

// resolver file exceeds line budget
type Gql08 struct{ Base }

func NewGql08() *Gql08 {
	return &Gql08{Base: Base{meta: Meta{ID: "gql-08", Gates: gqlGates, Domain: "graphql", DefaultSeverity: SeverityInfo}}}
}

func (c *Gql08) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	var findings []Finding
	for _, gf := range mod.GoSourceFiles() {
		if !isHandWrittenResolverRel(gf.RelPath) {
			continue
		}
		data, err := os.ReadFile(gf.Path)
		if err != nil {
			continue
		}
		if strings.Count(string(data), "\n")+1 <= gqlResolverMaxLines {
			continue
		}
		findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityInfo), gf.RelPath, 1))
	}
	return findings, nil
}

// get graphql query without size limit
type Gql09 struct{ Base }

func NewGql09() *Gql09 {
	return &Gql09{Base: Base{meta: Meta{ID: "gql-09", Gates: gqlGates, Domain: "graphql", DefaultSeverity: SeverityInfo}}}
}

func (c *Gql09) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := poolFor(mod, astutil.Filter{SkipTestFiles: true})
	if err != nil {
		return nil, err
	}
	if moduleHasHint(pool, querySizeLimitHints) {
		return nil, nil
	}
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !fileHasGetGraphQLQuery(f) {
			return true
		}
		call, ok := n.(*ast.CallExpr)
		if !ok || !isGetQueryParamCall(f, call) {
			return true
		}
		findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityInfo), f.RelPath, pool.Line(call)))
		return true
	})
	if len(findings) == 0 {
		for _, f := range pool.Files {
			if fileHasGetGraphQLQuery(f) {
				findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityInfo), f.RelPath, 1))
			}
		}
	}
	return findings, nil
}

// missing gqlgen.yml
type Gqlgen01 struct{ Base }

func NewGqlgen01() *Gqlgen01 {
	return &Gqlgen01{Base: Base{meta: Meta{ID: "gqlgen-01", Gates: []string{"gqlgen"}, Domain: "graphql", DefaultSeverity: SeverityFail}}}
}

func (c *Gqlgen01) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	for _, name := range []string{"gqlgen.yml", "gqlgen.yaml"} {
		if _, err := os.Stat(filepath.Join(mod.Root(), name)); err == nil {
			return nil, nil
		}
	}
	return []Finding{finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityFail), "gqlgen.yml", 1)}, nil
}

// federation entity resolver without auth check
type Gqlgen02 struct{ Base }

func NewGqlgen02() *Gqlgen02 {
	return &Gqlgen02{Base: Base{meta: Meta{ID: "gqlgen-02", Gates: []string{"gqlgen"}, Domain: "graphql", DefaultSeverity: SeverityWarn}}}
}

func (c *Gqlgen02) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := poolFor(mod, astutil.Filter{SkipTestFiles: true})
	if err != nil {
		return nil, err
	}
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !isEntityResolverFile(f.RelPath) {
			return true
		}
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Body == nil || fn.Name == nil {
			return true
		}
		if !strings.HasPrefix(fn.Name.Name, "Find") && !strings.HasPrefix(fn.Name.Name, "Entity") {
			return true
		}
		if funcHasAuthHint(fn) {
			return true
		}
		findings = append(findings, finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityWarn), f.RelPath, pool.Line(fn)))
		return true
	})
	return findings, nil
}

// no panic recovery at graphql execute boundary
type Ggl01 struct{ Base }

func NewGgl01() *Ggl01 {
	return &Ggl01{Base: Base{meta: Meta{ID: "ggl-01", Gates: []string{"graphql-go", "graphql"}, Domain: "graphql", DefaultSeverity: SeverityWarn}}}
}

func (c *Ggl01) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	if !moduleImportsGraphQLGo(mod) {
		return nil, nil
	}
	pool, err := poolFor(mod, astutil.Filter{SkipTestFiles: true})
	if err != nil {
		return nil, err
	}
	if moduleHasHint(pool, recoverHints) {
		return nil, nil
	}
	file, line, ok := firstGraphQLHandlerSetup(pool)
	if !ok {
		return nil, nil
	}
	return []Finding{finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityWarn), file, line)}, nil
}

// only legacy code-first graphql library
type Ggl02 struct{ Base }

func NewGgl02() *Ggl02 {
	return &Ggl02{Base: Base{meta: Meta{ID: "ggl-02", Gates: []string{"graphql-go", "graphql"}, Domain: "graphql", DefaultSeverity: SeverityInfo}}}
}

func (c *Ggl02) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	goMod := string(mod.GoModContent())
	if !strings.Contains(goMod, "github.com/graphql-go/graphql") {
		return nil, nil
	}
	if strings.Contains(goMod, "github.com/99designs/gqlgen") ||
		strings.Contains(goMod, "github.com/graph-gophers/graphql-go") {
		return nil, nil
	}
	return []Finding{finding(c.ID(), effectiveSeverity(mod, c.ID(), SeverityInfo), "go.mod", 1)}, nil
}

func isResolverFilePath(rel string) bool {
	rel = filepath.ToSlash(rel)
	return strings.Contains(rel, "/resolver/") || strings.Contains(rel, "/resolvers/")
}

func isGqlGeneratedFile(rel string) bool {
	base := filepath.Base(rel)
	return base == "generated.go" || base == "models_gen.go"
}

func isHandWrittenResolverFile(f *astutil.File) bool {
	return isHandWrittenResolverRel(f.RelPath)
}

func isHandWrittenResolverRel(rel string) bool {
	return isResolverFilePath(rel) && !astutil.IsTestFile(rel) && !isGqlGeneratedFile(rel)
}

func isEntityResolverFile(rel string) bool {
	base := filepath.Base(rel)
	return base == "entity.resolvers.go" || strings.Contains(base, "entity.resolver")
}

func loopBody(n ast.Node) *ast.BlockStmt {
	switch v := n.(type) {
	case *ast.ForStmt:
		return v.Body
	case *ast.RangeStmt:
		return v.Body
	default:
		return nil
	}
}

func isDbQueryCall(f *astutil.File, call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	name := sel.Sel.Name
	if _, ok := dbQueryMethods[name]; !ok {
		return false
	}
	if imp, resolved, ok := selectorImport(f, sel); ok {
		if !isSQLStorageImport(imp) {
			return false
		}
		_, ok = dbQueryMethods[resolved]
		return ok
	}
	if !looksLikeDBReceiver(sel.X) {
		return false
	}
	return fileHasSQLStorageImport(f) || isResolverFilePath(f.RelPath)
}

func fileHasBatchHint(f *astutil.File) bool {
	src := strings.ToLower(string(f.Src))
	for _, hint := range batchHints {
		if strings.Contains(src, strings.ToLower(hint)) {
			return true
		}
	}
	return false
}

func moduleHasGraphQLServer(mod ModuleView) bool {
	goMod := string(mod.GoModContent())
	return strings.Contains(goMod, "github.com/99designs/gqlgen") ||
		strings.Contains(goMod, "github.com/graph-gophers/graphql-go") ||
		strings.Contains(goMod, "github.com/graphql-go/graphql")
}

func moduleImportsGraphQLGo(mod ModuleView) bool {
	goMod := string(mod.GoModContent())
	return strings.Contains(goMod, "github.com/graph-gophers/graphql-go") ||
		strings.Contains(goMod, "github.com/graphql-go/graphql")
}

func moduleHasHint(pool *astutil.Pool, hints []string) bool {
	for _, f := range pool.Files {
		if astutil.IsTestFile(f.RelPath) {
			continue
		}
		src := string(f.Src)
		for _, hint := range hints {
			if strings.Contains(src, hint) {
				return true
			}
		}
	}
	return false
}

func firstGraphQLServerSetup(pool *astutil.Pool) (file string, line int, ok bool) {
	hints := []string{
		"github.com/99designs/gqlgen", "github.com/graph-gophers/graphql-go",
		"github.com/graphql-go/graphql", "handler.New", "graphql.Do", "relay.Handler",
	}
	for _, f := range pool.Files {
		if astutil.IsTestFile(f.RelPath) {
			continue
		}
		for _, hint := range hints {
			if strings.Contains(string(f.Src), hint) {
				return f.RelPath, 1, true
			}
		}
	}
	return "", 0, false
}

func firstGraphQLHandlerSetup(pool *astutil.Pool) (file string, line int, ok bool) {
	hints := []string{"graphql.Do", "relay.Handler", "graphql.Schema", "graphql.NewSchema"}
	for _, f := range pool.Files {
		if astutil.IsTestFile(f.RelPath) {
			continue
		}
		for _, hint := range hints {
			if strings.Contains(string(f.Src), hint) {
				return f.RelPath, 1, true
			}
		}
	}
	return "", 0, false
}

func fileHasIntrospection(f *astutil.File) bool { return f.ContainsAny(introspectionHints...) }

func introspectionLine(f *astutil.File) int {
	src := string(f.Src)
	for _, hint := range introspectionHints {
		if idx := strings.Index(src, hint); idx >= 0 {
			return strings.Count(src[:idx], "\n") + 1
		}
	}
	return 1
}

func fileHasPlayground(f *astutil.File) bool { return f.ContainsAny(playgroundHints...) }

func playgroundLine(f *astutil.File) int {
	src := string(f.Src)
	for _, hint := range playgroundHints {
		if idx := strings.Index(src, hint); idx >= 0 {
			return strings.Count(src[:idx], "\n") + 1
		}
	}
	return 1
}

func hasDevOrEnvGuard(src string) bool {
	if hasDevBuildTag(src) {
		return true
	}
	for _, g := range []string{
		"os.Getenv", "Getenv(", ".Env.", "cfg.", "config.",
		"IsDev", "IsProd", "IsProduction", "APP_ENV", "Environment",
	} {
		if strings.Contains(src, g) {
			return true
		}
	}
	return false
}

func isMapStringInterface(n ast.Node) bool {
	typ, ok := n.(*ast.MapType)
	if !ok {
		return false
	}
	key, ok := typ.Key.(*ast.Ident)
	if !ok || key.Name != "string" {
		return false
	}
	switch v := typ.Value.(type) {
	case *ast.InterfaceType:
		return true
	case *ast.Ident:
		return v.Name == "interface{}"
	case *ast.IndexExpr:
		if ident, ok := v.X.(*ast.Ident); ok && ident.Name == "interface" {
			return true
		}
	case *ast.IndexListExpr:
		if ident, ok := v.X.(*ast.Ident); ok && ident.Name == "interface" {
			return true
		}
	}
	return false
}

func funcHasAuthHint(fn *ast.FuncDecl) bool {
	if fn.Body == nil {
		return false
	}
	found := false
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		switch v := n.(type) {
		case *ast.Ident:
			for _, hint := range authHints {
				if strings.Contains(v.Name, hint) {
					found = true
					return false
				}
			}
		case *ast.SelectorExpr:
			for _, hint := range authHints {
				if strings.Contains(v.Sel.Name, hint) {
					found = true
					return false
				}
			}
		}
		return true
	})
	return found
}

func fileHasGetGraphQLQuery(f *astutil.File) bool {
	src := string(f.Src)
	return strings.Contains(src, "Query.Get(\"query\")") ||
		strings.Contains(src, "Query.Get(\"Query\")") ||
		(strings.Contains(src, "URL.Query()") && strings.Contains(src, "query"))
}

func isGetQueryParamCall(f *astutil.File, call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Get" || len(call.Args) != 1 {
		return false
	}
	lit, ok := call.Args[0].(*ast.BasicLit)
	if !ok {
		return false
	}
	val := strings.Trim(lit.Value, `"`)
	if val != "query" && val != "Query" {
		return false
	}
	return isQueryGetter(sel)
}

func isQueryGetter(sel *ast.SelectorExpr) bool {
	inner, ok := sel.X.(*ast.SelectorExpr)
	if !ok || inner.Sel.Name != "Query" {
		return false
	}
	ident, ok := inner.X.(*ast.Ident)
	if !ok {
		return false
	}
	return ident.Name == "URL" || ident.Name == "r" || ident.Name == "req"
}
