package check

import (
	"context"
	"go/ast"
	"go/token"
	"os"
	"regexp"
	"strconv"
	"strings"

	"github.com/gohaisee/refgrade/internal/astutil"
)

var (
	sqlMethodNames = map[string]struct{}{
		"Query": {}, "QueryRow": {}, "Exec": {},
		"Get": {}, "Select": {}, "Queryx": {}, "QueryRowx": {},
		"Find": {}, "First": {}, "Take": {}, "Last": {},
		"Create": {}, "Save": {}, "Delete": {}, "Raw": {}, "Scan": {},
	}

	sqlPackageCalls = map[string]map[string]struct{}{
		"database/sql":                    {"Open": {}},
		"github.com/jackc/pgx/v5":         {"Connect": {}},
		"github.com/jackc/pgx/v5/pgxpool":   {"New": {}, "NewWithConfig": {}},
		"github.com/jmoiron/sqlx":         {"Connect": {}, "Open": {}},
	}

	sqlKeywordsRe   = regexp.MustCompile(`(?i)\b(SELECT|INSERT|UPDATE|DELETE|FROM|WHERE)\b`)
	limitRe         = regexp.MustCompile(`(?i)\bLIMIT\b`)
	selectStarRe    = regexp.MustCompile(`(?i)SELECT\s+\*`)
	offsetRe        = regexp.MustCompile(`(?i)\bOFFSET\b`)
	moneyFieldRe    = regexp.MustCompile(`(?i)(amount|price|balance|cost|fee|money|total|payment|currency|revenue|salary|wage)`)
	sqlcGeneratedRe = regexp.MustCompile(`(?i)code generated by sqlc`)
)

func sqlGates() []string {
	return []string{"pgx", "gorm", "sqlx", "sqlc", "ent", "database/sql"}
}

func sqlInspect(mod ModuleView) (*astutil.Pool, error) {
	return poolFor(mod, astutil.Filter{SkipTestFiles: true})
}

func inspectLoopBody(pool *astutil.Pool, f *astutil.File, body ast.Node, id, sev string, findings *[]Finding) {
	if body == nil {
		return
	}
	ast.Inspect(body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		if isSQLDataCall(f, call) {
			*findings = append(*findings, finding(id, sev, f.RelPath, pool.Line(call)))
		}
		return true
	})
}

func isSQLDataCall(f *astutil.File, call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	if _, ok := sqlMethodNames[sel.Sel.Name]; ok {
		return true
	}
	imp, name, ok := f.Selector(sel)
	if !ok {
		return false
	}
	methods, ok := sqlPackageCalls[imp]
	if !ok {
		return false
	}
	_, ok = methods[name]
	return ok
}

func isPoolOpenCall(f *astutil.File, call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	imp, name, ok := selectorImport(f, sel)
	if !ok {
		return false
	}
	methods, ok := sqlPackageCalls[imp]
	if !ok {
		return false
	}
	_, ok = methods[name]
	return ok
}

func selectorImport(f *astutil.File, sel *ast.SelectorExpr) (importPath, name string, ok bool) {
	if imp, name, ok := f.Selector(sel); ok {
		return imp, name, true
	}
	ident, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", sel.Sel.Name, false
	}
	if imp, ok := importPathForIdent(f, ident.Name); ok {
		return imp, sel.Sel.Name, true
	}
	return "", sel.Sel.Name, false
}

func importPathForIdent(f *astutil.File, name string) (string, bool) {
	if p := f.ImportPathOf(name); p != "" {
		return p, true
	}
	for local, path := range f.Imports {
		if local == name {
			return path, true
		}
	}
	for _, path := range f.Imports {
		if name == "pgx" && strings.Contains(path, "jackc/pgx/v5") {
			return path, true
		}
	}
	return "", false
}

func isFmtSprintfSQL(call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Sprintf" {
		return false
	}
	ident, ok := sel.X.(*ast.Ident)
	if !ok || ident.Name != "fmt" {
		return false
	}
	if len(call.Args) < 2 {
		return false
	}
	lit, ok := call.Args[0].(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return false
	}
	return sqlKeywordsRe.MatchString(unquoteBasicLit(lit))
}

func unquoteBasicLit(lit *ast.BasicLit) string {
	s, err := strconv.Unquote(lit.Value)
	if err != nil {
		return strings.Trim(lit.Value, `"`)
	}
	return s
}

func isSQLString(s string) bool {
	return sqlKeywordsRe.MatchString(s)
}

func hasLimitInSQL(s string) bool {
	return limitRe.MatchString(s)
}

func hasSelectStar(s string) bool {
	return selectStarRe.MatchString(s)
}

func hasOffsetInSQL(s string) bool {
	return offsetRe.MatchString(s)
}

func isListFuncName(name string) bool {
	return strings.HasPrefix(name, "List") || strings.HasPrefix(name, "FindAll")
}

func funcBodySQLStrings(body *ast.BlockStmt) []string {
	if body == nil {
		return nil
	}
	var out []string
	ast.Inspect(body, func(n ast.Node) bool {
		lit, ok := n.(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			return true
		}
		s := unquoteBasicLit(lit)
		if isSQLString(s) {
			out = append(out, s)
		}
		return true
	})
	return out
}

func exprHasStringConcat(expr ast.Expr) bool {
	switch e := expr.(type) {
	case *ast.BinaryExpr:
		if e.Op != token.ADD {
			return false
		}
		_, leftStr := e.X.(*ast.BasicLit)
		_, rightStr := e.Y.(*ast.BasicLit)
		if leftStr || rightStr {
			return true
		}
		return exprHasStringConcat(e.X) || exprHasStringConcat(e.Y)
	default:
		return false
	}
}

func isMoneyFieldName(name string) bool {
	return moneyFieldRe.MatchString(name)
}

func isFloat64Type(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	return ok && ident.Name == "float64"
}

func isGormDBType(expr ast.Expr) bool {
	star, ok := expr.(*ast.StarExpr)
	if !ok {
		return false
	}
	sel, ok := star.X.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	ident, ok := sel.X.(*ast.Ident)
	return ok && ident.Name == "gorm" && sel.Sel.Name == "DB"
}

func isRemoteSSLModeDisable(s string) bool {
	lower := strings.ToLower(s)
	if !strings.Contains(lower, "sslmode=disable") {
		return false
	}
	if strings.Contains(lower, "localhost") || strings.Contains(lower, "127.0.0.1") {
		return false
	}
	return strings.Contains(s, "@") || strings.Contains(lower, "host=")
}

func isErrErrorStringCompare(n ast.Node) bool {
	switch node := n.(type) {
	case *ast.BinaryExpr:
		if node.Op != token.EQL && node.Op != token.NEQ {
			return false
		}
		return isErrErrorExpr(node.X) || isErrErrorExpr(node.Y)
	case *ast.CallExpr:
		sel, ok := node.Fun.(*ast.SelectorExpr)
		if !ok {
			return false
		}
		ident, ok := sel.X.(*ast.Ident)
		if !ok || ident.Name != "strings" {
			return false
		}
		switch sel.Sel.Name {
		case "Contains", "HasPrefix", "HasSuffix", "EqualFold":
			for _, arg := range node.Args {
				if isErrErrorExpr(arg) {
					return true
				}
			}
		}
	}
	return false
}

func isErrErrorExpr(expr ast.Expr) bool {
	call, ok := expr.(*ast.CallExpr)
	if !ok {
		return false
	}
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Error" {
		return false
	}
	ident, ok := sel.X.(*ast.Ident)
	return ok && ident.Name == "err"
}

func countPreloadChain(call *ast.CallExpr) int {
	count := 0
	cur := call
	for {
		sel, ok := cur.Fun.(*ast.SelectorExpr)
		if !ok {
			break
		}
		if sel.Sel.Name == "Preload" {
			count++
		}
		inner, ok := sel.X.(*ast.CallExpr)
		if !ok {
			break
		}
		cur = inner
	}
	return count
}

func callEndsWithFind(call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	return ok && sel.Sel.Name == "Find"
}

func isGormPreloadFindChain(call *ast.CallExpr) bool {
	if !callEndsWithFind(call) {
		return false
	}
	return countPreloadChain(call) >= 2
}

func isEntTraversal(sel *ast.SelectorExpr) bool {
	return sel.Sel.Name == "Edges"
}

func fileImportsGorm(f *astutil.File) bool {
	return fileImportsPath(f, "gorm.io/gorm")
}

func fileImportsSqlx(f *astutil.File) bool {
	return fileImportsPath(f, "github.com/jmoiron/sqlx")
}

func fileImportsEnt(f *astutil.File) bool {
	if fileImportsPath(f, "entgo.io/ent") {
		return true
	}
	for _, spec := range f.AST.Imports {
		path := strings.Trim(spec.Path.Value, `"`)
		if path == "entgo.io/ent" || strings.HasPrefix(path, "entgo.io/ent/") {
			return true
		}
	}
	return false
}

func isSqlxNoCtxCall(f *astutil.File, call *ast.CallExpr) bool {
	if !fileImportsSqlx(f) {
		return false
	}
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	switch sel.Sel.Name {
	case "Get", "Select":
		return true
	default:
		return false
	}
}

// Query/Exec/orm call inside for loop
type Sql01 struct{ Base }

func NewSql01() *Sql01 {
	return &Sql01{Base: Base{meta: Meta{ID: "sql-01", Gates: sqlGates(), Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Sql01) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		switch loop := n.(type) {
		case *ast.ForStmt:
			inspectLoopBody(pool, f, loop.Body, c.ID(), sev, &findings)
		case *ast.RangeStmt:
			inspectLoopBody(pool, f, loop.Body, c.ID(), sev, &findings)
		}
		return true
	})
	return findings, nil
}

// sql built with fmt.Sprintf and variable args
type Sql02 struct{ Base }

func NewSql02() *Sql02 {
	return &Sql02{Base: Base{meta: Meta{ID: "sql-02", Gates: sqlGates(), Domain: "sql", DefaultSeverity: SeverityFail}}}
}

func (c *Sql02) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityFail)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok || !isFmtSprintfSQL(call) {
			return true
		}
		findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(call)))
		return true
	})
	return findings, nil
}

// List*/FindAll* without LIMIT in sql
type Sql03 struct{ Base }

func NewSql03() *Sql03 {
	return &Sql03{Base: Base{meta: Meta{ID: "sql-03", Gates: sqlGates(), Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Sql03) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Body == nil || fn.Name == nil {
			return true
		}
		if !isListFuncName(fn.Name.Name) {
			return true
		}
		sqls := funcBodySQLStrings(fn.Body)
		if len(sqls) == 0 {
			return true
		}
		for _, s := range sqls {
			if !hasLimitInSQL(s) {
				findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(fn)))
				break
			}
		}
		return true
	})
	return findings, nil
}

// SELECT * in sql string
type Sql04 struct{ Base }

func NewSql04() *Sql04 {
	return &Sql04{Base: Base{meta: Meta{ID: "sql-04", Gates: sqlGates(), Domain: "sql", DefaultSeverity: SeverityInfo}}}
}

func (c *Sql04) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityInfo)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		lit, ok := n.(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			return true
		}
		if hasSelectStar(unquoteBasicLit(lit)) {
			findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(lit)))
		}
		return true
	})
	return findings, nil
}

// pool open inside handler package
type Sql05 struct{ Base }

func NewSql05() *Sql05 {
	return &Sql05{Base: Base{meta: Meta{ID: "sql-05", Gates: sqlGates(), Domain: "sql", DefaultSeverity: SeverityFail}}}
}

func (c *Sql05) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityFail)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !isHandlerPackage(f.RelPath) {
			return true
		}
		call, ok := n.(*ast.CallExpr)
		if !ok || !isPoolOpenCall(f, call) {
			return true
		}
		findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(call)))
		return true
	})
	return findings, nil
}

// float64 field with money-like name
type Sql06 struct{ Base }

func NewSql06() *Sql06 {
	return &Sql06{Base: Base{meta: Meta{ID: "sql-06", Gates: sqlGates(), Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Sql06) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		field, ok := n.(*ast.Field)
		if !ok {
			return true
		}
		if field.Type == nil || !isFloat64Type(field.Type) {
			return true
		}
		for _, name := range field.Names {
			if isMoneyFieldName(name.Name) {
				findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(name)))
			}
		}
		return true
	})
	return findings, nil
}

// OFFSET in sql string or comment
type Sql07 struct{ Base }

func NewSql07() *Sql07 {
	return &Sql07{Base: Base{meta: Meta{ID: "sql-07", Gates: sqlGates(), Domain: "sql", DefaultSeverity: SeverityInfo}}}
}

func (c *Sql07) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityInfo)
	var findings []Finding
	for _, f := range pool.Files {
		for _, cg := range f.AST.Comments {
			for _, cmt := range cg.List {
				if hasOffsetInSQL(cmt.Text) {
					findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(cmt)))
				}
			}
		}
	}
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		lit, ok := n.(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			return true
		}
		if hasOffsetInSQL(unquoteBasicLit(lit)) {
			findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(lit)))
		}
		return true
	})
	return findings, nil
}

// pgx.Connect instead of pool
type Pgx01 struct{ Base }

func NewPgx01() *Pgx01 {
	return &Pgx01{Base: Base{meta: Meta{ID: "pgx-01", Gates: []string{"pgx"}, Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Pgx01) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "Connect" {
			return true
		}
		imp, _, ok := selectorImport(f, sel)
		if !ok || !strings.Contains(imp, "jackc/pgx/v5") || sel.Sel.Name != "Connect" {
			return true
		}
		findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(call)))
		return true
	})
	return findings, nil
}

// postgres error compared by string
type Pgx02 struct{ Base }

func NewPgx02() *Pgx02 {
	return &Pgx02{Base: Base{meta: Meta{ID: "pgx-02", Gates: []string{"pgx"}, Domain: "sql", DefaultSeverity: SeverityInfo}}}
}

func (c *Pgx02) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityInfo)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if isErrErrorStringCompare(n) {
			findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(n)))
		}
		return true
	})
	return findings, nil
}

// sslmode=disable in remote dsn
type Pgx03 struct{ Base }

func NewPgx03() *Pgx03 {
	return &Pgx03{Base: Base{meta: Meta{ID: "pgx-03", Gates: []string{"pgx"}, Domain: "sql", DefaultSeverity: SeverityFail}}}
}

func (c *Pgx03) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityFail)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		lit, ok := n.(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			return true
		}
		if isRemoteSSLModeDisable(unquoteBasicLit(lit)) {
			findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(lit)))
		}
		return true
	})
	return findings, nil
}

// db.Raw with string concatenation
type Gorm01 struct{ Base }

func NewGorm01() *Gorm01 {
	return &Gorm01{Base: Base{meta: Meta{ID: "gorm-01", Gates: []string{"gorm"}, Domain: "sql", DefaultSeverity: SeverityFail}}}
}

func (c *Gorm01) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityFail)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !fileImportsGorm(f) {
			return true
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "Raw" || len(call.Args) == 0 {
			return true
		}
		if exprHasStringConcat(call.Args[0]) {
			findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(call)))
		}
		return true
	})
	return findings, nil
}

// 2+ Preload chain on Find in handler/List*
type Gorm02 struct{ Base }

func NewGorm02() *Gorm02 {
	return &Gorm02{Base: Base{meta: Meta{ID: "gorm-02", Gates: []string{"gorm"}, Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Gorm02) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	var inListFn bool
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !fileImportsGorm(f) {
			return true
		}
		if fn, ok := n.(*ast.FuncDecl); ok && fn.Name != nil {
			inListFn = isListFuncName(fn.Name.Name)
			return true
		}
		call, ok := n.(*ast.CallExpr)
		if !ok || !isGormPreloadFindChain(call) {
			return true
		}
		if !inListFn && !isHandlerPackage(f.RelPath) {
			return true
		}
		findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(call)))
		return true
	})
	return findings, nil
}

// AutoMigrate in cmd/
type Gorm03 struct{ Base }

func NewGorm03() *Gorm03 {
	return &Gorm03{Base: Base{meta: Meta{ID: "gorm-03", Gates: []string{"gorm"}, Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Gorm03) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !astutil.IsCmdFile(f.RelPath) || !fileImportsGorm(f) {
			return true
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "AutoMigrate" {
			return true
		}
		findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(call)))
		return true
	})
	return findings, nil
}

// Debug() when gorm imported
type Gorm04 struct{ Base }

func NewGorm04() *Gorm04 {
	return &Gorm04{Base: Base{meta: Meta{ID: "gorm-04", Gates: []string{"gorm"}, Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Gorm04) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !fileImportsGorm(f) {
			return true
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "Debug" {
			return true
		}
		findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(call)))
		return true
	})
	return findings, nil
}

// package-level var *gorm.DB
type Gorm05 struct{ Base }

func NewGorm05() *Gorm05 {
	return &Gorm05{Base: Base{meta: Meta{ID: "gorm-05", Gates: []string{"gorm"}, Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Gorm05) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !fileImportsGorm(f) {
			return true
		}
		gen, ok := n.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			return true
		}
		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || vs.Type == nil || !isGormDBType(vs.Type) {
				continue
			}
			for _, name := range vs.Names {
				findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(name)))
			}
		}
		return true
	})
	return findings, nil
}

// Get/Select without Context when sqlx imported
type Sqlx01 struct{ Base }

func NewSqlx01() *Sqlx01 {
	return &Sqlx01{Base: Base{meta: Meta{ID: "sqlx-01", Gates: []string{"sqlx"}, Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Sqlx01) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok || !isSqlxNoCtxCall(f, call) {
			return true
		}
		findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(call)))
		return true
	})
	return findings, nil
}

// *.sql.go without sqlc generated header
type Sqlc01 struct{ Base }

func NewSqlc01() *Sqlc01 {
	return &Sqlc01{Base: Base{meta: Meta{ID: "sqlc-01", Gates: []string{"sqlc"}, Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Sqlc01) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	for _, gf := range mod.GoSourceFiles() {
		if !strings.HasSuffix(gf.RelPath, ".sql.go") {
			continue
		}
		data, err := os.ReadFile(gf.Path)
		if err != nil {
			continue
		}
		if !sqlcGeneratedRe.MatchString(string(data)) {
			findings = append(findings, finding(c.ID(), sev, gf.RelPath, 1))
		}
	}
	return findings, nil
}

// edge traversal or Query inside loop when ent imported
type Ent01 struct{ Base }

func NewEnt01() *Ent01 {
	return &Ent01{Base: Base{meta: Meta{ID: "ent-01", Gates: []string{"ent"}, Domain: "sql", DefaultSeverity: SeverityWarn}}}
}

func (c *Ent01) Run(ctx context.Context, mod ModuleView) ([]Finding, error) {
	_ = ctx
	if checkDisabled(mod, c.ID()) {
		return nil, nil
	}
	pool, err := sqlInspect(mod)
	if err != nil {
		return nil, err
	}
	sev := effectiveSeverity(mod, c.ID(), SeverityWarn)
	var findings []Finding
	pool.Inspect(func(f *astutil.File, n ast.Node) bool {
		if !fileImportsEnt(f) {
			return true
		}
		var body ast.Node
		switch loop := n.(type) {
		case *ast.ForStmt:
			body = loop.Body
		case *ast.RangeStmt:
			body = loop.Body
		default:
			return true
		}
		ast.Inspect(body, func(n ast.Node) bool {
			sel, ok := n.(*ast.SelectorExpr)
			if !ok || !isEntTraversal(sel) {
				return true
			}
			findings = append(findings, finding(c.ID(), sev, f.RelPath, pool.Line(sel)))
			return true
		})
		return true
	})
	return findings, nil
}
